name: formigas_core_pipeline_test
description: testing github actions
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  formigas_mvc:
    path: lib-formigas-mvc
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_annotation: ^4.8.1


dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
