name: Flutter CI

on:
  push:
    branches: [develop, staging, master, main]
  pull_request:

env:
  FLUTTER_VERSION: "3.13.9"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Validate
        run: |
          cd {{project_name.snakeCase()}}
          dart format -o none --set-exit-if-changed lib/ test/
          dart run build_runner build --delete-conflicting-outputs
          flutter analyze --fatal-infos --fatal-warnings

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Determine Flavor
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "flavor=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
          echo "flavor=staging" >> $GITHUB_ENV
          else
          echo "flavor=development" >> $GITHUB_ENV
          fi
      - name: Build Android
        run: |
          cd {{project_name.snakeCase()}}
          flutter clean
          dart run build_runner build --delete-conflicting-outputs
          flutter build appbundle --debug --flavor ${{ env.flavor }} -t lib/main_${{ env.flavor }}.dart

  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Determine Flavor
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "flavor=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
          echo "flavor=staging" >> $GITHUB_ENV
          else
          echo "flavor=development" >> $GITHUB_ENV
          fi
      - name: Build iOS
        run: |
          cd {{project_name.snakeCase()}}
          flutter clean
          dart run build_runner build --delete-conflicting-outputs
          flutter build ios --debug --flavor ${{ env.flavor }} -t lib/main_${{ env.flavor }}.dart --no-codesign

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Test
        run: |
          flutter pub global activate junitreport
          set -o pipefail
          cd {{project_name.snakeCase()}}
          flutter clean
          dart run build_runner build --delete-conflicting-outputs
          flutter test --machine --coverage | tee >( $HOME/.pub-cache/bin/tojunit > test-report-app.xml )
          flutter pub global activate cobertura
          $HOME/.pub-cache/bin/cobertura convert -i coverage/lcov.info -o coverage/cobertura.xml -p pubspec.yaml
          sudo apt update && sudo apt install -y lcov
          genhtml -o docs/coverage/ --no-function-coverage --no-branch-coverage coverage/lcov.info
          lcov --list coverage/lcov.info
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage Report
          path: |
            {{project_name.snakeCase()}}/coverage/lcov.info
            {{project_name.snakeCase()}}/coverage/cobertura.xml
            {{project_name.snakeCase()}}/docs/coverage/
          retention-days: 7
