name: Continuous Integration

on:
  push:
    branches: [develop, staging, master, main]
  pull_request:

env:
  FLUTTER_VERSION: "3.13.9"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Format
        run: dart format -o none --set-exit-if-changed lib/ test/
      - name: Build runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze --fatal-infos --fatal-warnings

  determine-flavor:
    runs-on: ubuntu-latest
    outputs:
      flavor: ${{ steps.set-flavor.outputs.flavor }}
    steps:
      - name: Determine Flavor
        id: set-flavor
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "flavor=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "flavor=staging" >> $GITHUB_OUTPUT
          else
            echo "flavor=development" >> $GITHUB_OUTPUT
          fi

  build_app:
    needs: determine-flavor
    strategy:
      matrix:
        platform: [android, ios]
        include:
          - runs-on: ubuntu-latest
            platform: android
          - runs-on: macos-latest
            platform: ios
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - name: Build ${{ matrix.platform }} ${{ needs.determine-flavor.outputs.flavor }}
        uses: ./.github/actions/build_app
        with:
          platform: ${{ matrix.platform }}
          flavor: ${{ needs.determine-flavor.outputs.flavor }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
      - name: Setup
        run: |
          flutter pub global activate junitreport
          set -o pipefail
      - name: Clean
        run: flutter clean
      - name: Build runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Test
        run: flutter test --machine --coverage | tee >( $HOME/.pub-cache/bin/tojunit > test-report-app.xml )
      - name: Convert to Cobertura
        run: |
          flutter pub global activate cobertura
          $HOME/.pub-cache/bin/cobertura convert -i coverage/lcov.info -o coverage/cobertura.xml -p pubspec.yaml
      - name: Generate Coverage Report
        run: |
          sudo apt update && sudo apt install -y lcov
          genhtml -o docs/coverage/ --no-function-coverage --no-branch-coverage coverage/lcov.info
          lcov --list coverage/lcov.info
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage Report
          path: |
            coverage/lcov.info
            coverage/cobertura.xml
            docs/coverage/
          retention-days: 7
